### ISSUE TITLE
[10.0] WARNING: Deprecated method TestDefaultGetModel.default_get

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/addons-vauxoo#1145]
### [T#6664](https://www.vauxoo.com/web#id=6664&view_type=form&model=project.task&menu_id=136&action=138)

In the module `test_sale_team_warehouse` there is a warning that is showing up in server logs when using its version 10.0

```python
2016-12-27 12:32:58,617 16908 WARNING ? odoo.api: Deprecated method TestDefaultGetModel.default_get in module odoo.addons.test_sale_team_warehouse.models.test_model
```

**Comment by zaoral** [comment]
Hi @osvalr 

I'm familiar with this module.
I was surprised with this issue because I am not aware that default_get ORM method has been deprecated.
I just make a quick search in Odoo 10.0 repo and documentation. I did not find a mention about this method deprecated. Also I observe that a lot of odoo addons modules still use default_get method.

My second step was review the code of the  test_sale_team_warehouse module. I have an hypothesis: the method is not deprecated, instead, the api used in the method is the one deprecated: The method is in v7 api. Please could you try to change the method api, only need to add a @api.model decorator and replace the default_get() arguments with `(self, fields)`.

I think this could be a solution for your current warning.
From my PoV I think the steps to do related to this issue is to:

1. Make the POC, and if it works:
2. Review inside @vauxoo repositories all the default_get definition related to branch 10.0 in order to update the method api.
3. Maybe we can suggest to odoo change the message showed in the server log, just because can generate some type of confusion

Please could you apply the POC?
I will way for yout results

Best Regards

**Comment by osvalr** [comment]
@zaoral it is a matter of migration of the module, your second hypothesis is right, POC tested

**Comment by osvalr** [comment]
@zaoral I think that disabling the module should be okay, in case is needed should be fully migrated and not just that single method. What do you think?

**Comment by zaoral** [comment]
> @zaoral I think that disabling the module should be okay, in case is needed should be fully migrated and not just that single method. What do you think?

Indeed, this module should be completed updated to new API. I think two PR are needed: 1) fix the puntual warning just to avoid that annoying yellow message, 2) Whole module API Change.

However, before doing this I think that we need to evaluate if this module is really necessary in version 10.0. As far I remember sale teams in v10 are manage in different way.

@nhomar 
Please could you tell us if this module, should or should not be in 10.0 branch? This module is a test module related to the module [default_warehouse_from_sale_team](https://github.com/Vauxoo/addons-vauxoo/tree/8.0/default_warehouse_from_sale_team) in which we previously worked on branch 8.0

**Comment by zaoral** [comment]
@nhomar 
Please let us know your PoV here

Best Regards
