### ISSUE TITLE
Are account_advance_payment sale_double_validation migrated to v8?

### ISSUE THREAD

**Issue by sm2x** [Vauxoo/addons-vauxoo#171]
I was trying some addons namely 
- account_advance_payment
- sale_double_validation
  But they will not even install successfully on latest odoo v8 git pull.

**Comment by nhomar** [comment]
Hello @sm2x 

We migrate modules on this repository just when customer which finance them ask us for migrate it, if not, we remove it, in the case of such both modules, I think the are not migrated yet for differents reasons,

The Second one is because we were not asked for migration yet, the first one is more a PoC, if you can migrate them I should be really thankful and a PR should be welcome, if you don't have the skill I encourage to you to buy some little hours of consultancy to migrate them for everybody, until now they are not in our migration roadmap yet.

I hope you understand and thanks for test our public job, if you have any further question we are open to help you out.

Regards.
