### ISSUE TITLE
empty index.html in description causes error in interface

### ISSUE THREAD

**Issue by flotho** [Vauxoo/addons-vauxoo#330]
Hy,

Some modules have index.html empty in static folder.
For those modules, trying to reach the module description causes an xml error.

**Comment by nhomar** [comment]
@flotho 
Can you point me which one? and in what version?

We use this repository in production and we do not have any error can you show me what you are seeing?

Regard.

**Comment by zaoral** [comment]
@nhomar I confirm this bug.
Somo modules developed in v7 were imported to v8 and have empty index.html.

The problem occurs when loading the module.description in a v8 runing instance will raise an exception when trying to show the modules page.

We have two solutions. Remove the empty index.html files. Or add a basic html info for thouse empty index.html files.

@flotho there is two workarounds you can apply right now that will let you install the module you want until this problem is solve.
- Functional approach: Go to modules list view and select the modules you want to install using the checkbox. Then go up and select 'More' button an select 'Module inmediate install'.
- Technical approach: run your server adding the extra  -i module_name.

**Comment by nhomar** [comment]
Duplicated from issue #330
