### ISSUE TITLE
[fix] USER_STORY_SCRUM: image VAUXOO.png wrongly referenced.

### ISSUE THREAD

**Issue by nhomar** [Vauxoo/addons-vauxoo#375]

**Comment by zaoral** [comment]
Start working on this issue.
Task [vx#3887](https://www.vauxoo.com/web#id=3887&view_type=form&model=project.task&action=138)

**Comment by zaoral** [comment]
@nhomar this problem is already resolved.

![image](https://cloud.githubusercontent.com/assets/7593953/8910679/c02fc17c-344d-11e5-804a-0aaf68d3e97a.png)

However, the index.html description reflects User Story copy instead User Story Scrum module description. I will fix this runing Vauxoo/gist-vauxoo/description2html script to extract the User Story Scrum module README.md description and add it to the index.html file.

Regards.
