### ISSUE TITLE
add unit test for purchase_order_line_sequence

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/addons-vauxoo#511]
module: purchase_order_line_sequence

this module could fail from other unit test.
change logic of context
# TODO
- [ ] api.one and api.depends for constraint
- [ ] add module unit tests.

**Comment by moylop260** [comment]
@zaoral 
[purchase_order_line_sequence comment](https://github.com/Vauxoo/yoytec/pull/266#issuecomment-153049378)
"""
@moylop260 @nhomar the reason why the `purchase_order_line_sequence` module was used instead the one in the oca `purchase_order_reorder_lines` is that this last module has inconsistencies. Add a sequence field but this is not unique and is the same for all lines. Also the oca module use the purchase order line sequence to pass to the invoice lines and another stuffs.  

In our clients instance, we were searching for a way to identify the purchase order lines instead. This means that we want consecutive sequences the goal is to enumerate the purchase order lines in order to identify each one. We dont require to pass this sequence to the invoice lines.

For that the `purchase_order_line_sequence` module was created in addons-vauxoo. This make the enumeration when adding the purchase order lines via interface. Will sum one point to every line.

To do not present this same error when creating a purchase order from outside the interface we need to add the order_line key to the context like @moylop260 did. Or, we could have a new approach for the `purchase_order_line_sequence` in which we do not depend on the interface. 

I report this issue days ago looking to the future bugs we can found. The work required to fix the `purchase_order_line_sequence`  could be do in this Issue https://github.com/Vauxoo/addons-vauxoo/issues/511

Best Regards
"""

**Comment by moylop260** [comment]
@zaoral 
Could you use `api.depends` and `api.onchange` for avoid raises from orm creation (without view)?
And add unittest of `create` from orm

**Comment by moylop260** [comment]
NOTE: If is very hard the api.depends or not working... then we could consider to delete the contraint. (Maybe)

**Comment by zaoral** [comment]
Ok @moylop260 . I agreed, doing the unit test would tell us if this is api.depends approach would work. if not. I will remove the constraint.

Let you know when this is ready.
Best Regards.
