### ISSUE TITLE
Error running sale_double_validation

### ISSUE THREAD

**Issue by js-landoo** [Vauxoo/addons-vauxoo#695]
Hi Nhomar & Cia!

I'm testing sale_double_validation module for a possible new customer, but when I run wizard to assign an authorized group, I get a Traceback. I'm using last version (downloaded today).
I've tried selecting different groups, and it's allways the same problem.
Can you help me? Many thanks!

Josean
Avanzosc

```

 File "/home/josean/odoo/curso_nov14/other_addons/sale_double_validation/model/sale_double_validation_installer.py", line 57, in execute
    transition_obj.write(cr, uid, waiting_id, {'group_id': group_id})
  File "/home/josean/odoo/curso_nov14/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/josean/odoo/curso_nov14/server/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/josean/odoo/curso_nov14/server/openerp/models.py", line 3787, in write
    self._write(old_vals)
  File "/home/josean/odoo/curso_nov14/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/josean/odoo/curso_nov14/server/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/josean/odoo/curso_nov14/server/openerp/models.py", line 3898, in _write
    cr.execute(query, params + (sub_ids,))
  File "/home/josean/odoo/curso_nov14/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/josean/odoo/curso_nov14/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "group_id" is of type integer but expression is of type record
LINE 1: UPDATE "wkf_transition" SET "group_id"=(10, 'Ventas / Respon...
                                               ^
HINT:  You will need to rewrite or cast the expression.

```

**Comment by nhomar** [comment]
@hbto This module mentioned cames up in 2012 by you, is this being used yet?

@jsoroa Sadly this module is not migrated/touched technically since 2012 it is not migrated yet, can you tell us what is the use cas eyou are looking for? in order to decide if we migrate it ior simply propose you a different alternative?

**Comment by js-landoo** [comment]
Hi Nhomar, thanks for your fast reply.
We are in first analisis with this customer, but seems that they need exactly the same behaviour of purchase_double_validation. 
- Sales managers have to aprove quotations before they are sended to customer. This is the important funcionality.
- Each group of sale agents have a sales manager asigned. This could be not exact.

Regards

**Comment by nhomar** [comment]
Hello @jsoroa 

THis module do the same than sale_double_validation but it has not being touched since v6.

It is a very basic module, if you need it migrated we can plan something interesting here.

Are you interested on such development? if Yes!

Jus tput the plan here and we cann discuss such feature.

But I recommend look for an option where you do not pay extra, I think OCA has something if not, please let us know if you are interested on migrate this one and propose to OCA or left here.

regards.

**Comment by nonofpy** [comment]
You can try 
change "group_id" to "group_id[0]" in sale_double_validation_installer.py
