### ISSUE TITLE
[product_extended_segmentation] Price don't get updated when is lesser, a new behavior

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/addons-vauxoo#703]
I see that a new behavior (feature) on master branch in commit https://github.com/Vauxoo/addons-vauxoo/commit/c3930d76d7c9ff4187e9ddaad070621d31ef8e1b in #702 it updates the product cost only when the new one is higher (or equal), and I have some doubts about this:
- How it is supported this, what is the general rule that address to only get the cost updated when the price is higher?
- Can be a context flag a wildcard for this?

This is ONLY to clarify things that I am (and maybe others are) missing related to this point

**Comment by osvalr** [comment]
@hbto @nhomar have you seen this already?

**Comment by nhomar** [comment]
@osvalr 

This is a custom check asked for the customer in order to log correctly the automatic behavior in th cronjob.

The use is when it apply is mostly in the first run of the wizard after install the segmentation feature, there the customer did not update yet all his products.

Then we prefer cowardly not update the cost through cron sending such information, then the customer simply fix childs and then the cost in 99% of cases will increase.

The other point is that if the cost need to be checked over a threshold it will be configured (not yet the logic is managed in that ways) but it is the plan.

The point is now create a test that for the initialitazion data strategy in order to force run such check and assert that :+1:
1. Cost did not change.
2. Message was correctly logged.

Regards.

**Comment by osvalr** [comment]
#718 is getting this fixed

**Comment by osvalr** [comment]
This was fixed with #718
