### ISSUE TITLE
Petty Cash and Cash Advance management question (hr_expense_replenishment)

### ISSUE THREAD

**Issue by okuryan** [Vauxoo/addons-vauxoo#717]
Hi Nhomar and the rest of Vauxoo Team =) ,

Finally have analyzed your module hr_expense_replenishment. Module looks great and even works on Odoo 8 with no changes.
In general we see that workflow look like on image below:
![screen shot 2016-02-04 at 18 51 21](https://cloud.githubusercontent.com/assets/2680904/12820487/52fb46d4-cb70-11e5-82de-2977d3df88bc.png)

The question that I have now and that is not clear to me - how employee requests cash advance? Is it just asking Finance team by words? Not through Odoo?
And than Finance team when giving money just record that in Supplier Payments?

**Comment by hbto** [comment]
Hi @okuryan 

Great analysis that of yours,

> The question that I have now and that is not clear to me - how employee requests cash advance? Is it just asking Finance team by words? Not through Odoo?
> And than Finance team when giving money just record that in Supplier Payments?

So far that is the way it works
Employee ask advance by words off-odoo & that advance is record as a Supplier Payment.

Best Regards.

**Comment by zaoral** [comment]
@okuryan thanks for the analysis. I think could be an improve if you would like to add your workflow image to the module description.

Best Regards

**Comment by okuryan** [comment]
@hbto, good, than we implement way to ask in system. Just in big companies asking by words will not work.
@zaoral, sure. We can give you image of better quality, can you add it to module?

**Comment by hbto** [comment]
> @hbto, good, than we implement way to ask in system. Just in big companies asking by words will not work.

Excellent, if you want, make your implementation, and we could be happy to merge your new module in our branch, credit will be yours.

> @zaoral, sure. We can give you image of better quality, can you add it to module

Good we are seeking to put your image in our descriptor.

Best Regards.

**Comment by zaoral** [comment]
@okuryan Of course. If you can send a image with better quality please send it to kathy@vauxoo.com. If not, I will use the same image do put in this issue.

Either way I can take care of making the PR.
Best Regards.

**Comment by hbto** [comment]
> @okuryan Of course. If you can send a image with better quality please send it to kathy@vauxoo.com. If not, I will use the same image do put in this issue.

Or just attach it here.

Best Regards.

**Comment by okuryan** [comment]
@hbto, sent to your mail

**Comment by zaoral** [comment]
The image was added to the module description.
Thank you @okuryan

**Comment by hbto** [comment]
I will close this issue @okuryan 
If you need to open it again, do not hesitate

Best Regards

**Comment by ojobello** [comment]
I have read all the threads and we have a cash advance module that:

a) Allows cash limits for be set for employees
b) Controls which kind of expenditure an employee can spend on
c) Allows employee to make requests for cash giving reasons. Requests goes through the necessary approval
d) If employee is within limits of cash allowed, the request will be approved. Otherwise, request is rejected and employee has to make retirement of previous expenses
e) Once the request is approved, the Accounts who are actually in charge of payment will see the approved request and can disburse.
f) Disbursed cash is charged to the employee account eg Dr. Staff Advance Account and Cr. Cash/Bank
g) Employee goes to spend money on behalf of the company. After spending, employee makes a retirement of how he has spent the money. The submission of expenses is reviewed and approved by the Manager. The employee is also able to code the type of expenses he has made so that the accounts don't need to encode this again.
h) Once the expense is approved, system raises a journal to Dr. Expense, Cr. Staff Advance Account. 
i) It is possible that there is a cash required for refund to company. In this case, we have a refund feature where employee can take cash to Accountant and accountant will use the feature in this module to accept the cash refunded. Immediately this is validated, entries will be generated, Dr. Cash, Cr. Staff Advance Account
j) We can run a statement for each employee showing their Staff Advance Account and the balance due to or from the company at any point in time

This module is developed for v7, 8 and 9 and working well for all our clients.

**Comment by hbto** [comment]
Thanks for your comments @ojobello 

But as your comments don't add up to this conversation,

It is more of a post in a mailing list

I will take the liberty of getting rid of your comment and 
you are free of commenting on odoo mailing list with this
same wording you have post regards

**Comment by ojobello** [comment]
Not sure what it means when you say “my comments don’t add up to this conversation”. Please educate me.

Dare
