### ISSUE TITLE
[8.0-account_model_plans] Generated entries do not have distribution

### ISSUE THREAD

**Issue by cvinh** [Vauxoo/addons-vauxoo#961]
Steps to reproduce : 
- install account_model_plans
- create a account_model with an analytic distribution in a model line
- generate entries
- open the generated entry

Expected behaviour : 
The analytic distribution should be in generated entries

**Comment by cvinh** [comment]
out of scope personal question to hbto : did you overwrite write method for account_analytic_plan_instance in v8 ?

**Comment by hbto** [comment]
@invitu 

> Expected behaviour : 
> The analytic distribution should be in generated entries

I am checking this issue, as that feature was intented to work on v7

>  did you overwrite write method for account_analytic_plan_instance in v8 ?

I did overwrite the write method for account_analytic_plan_instance on v7, not yet for v8,

I have done that on a private project for a customer,

I have never liked that way of plans to work on the write method (personal thoughts)

**Comment by cvinh** [comment]
@hbto could you share your write method for plans please ?

**Comment by hbto** [comment]
@invitu This is still in my queue for things to do

**Comment by cvinh** [comment]
@hbto 

> I did overwrite the write method for account_analytic_plan_instance on v7, not yet for v8,

could you share your v7 write method for account_analytic_plan_instance ?

**Comment by hbto** [comment]
@invitu 

Sorry for late reply, I hope this could be helpful for you
What I actually did was getting rid of the write code,
I still think that this code could be improved but not useful
the way it is right now,

[account_analytic_plans.py.diff.txt](https://github.com/Vauxoo/addons-vauxoo/files/310143/account_analytic_plans.py.diff.txt)

My apologies because of my big delay.

Regards.

**Comment by cvinh** [comment]
@hbto
Thank you for your reply, you just comment out the write function ?
So it's a patch...
I thought you were overwriting the method with another one.
By the way (still personal question that I should ask to the community), In order to avoid patching the official addons, how can I do a module that deletes the account_analytic_plans write method ? I don't find the way to do it...

**Comment by cvinh** [comment]
back to scope, I did a PR : https://github.com/Vauxoo/addons-vauxoo/pull/990

**Comment by hbto** [comment]
@invitu 

> By the way (still personal question that I should ask to the community), In order to avoid patching the official addons, how can I do a module that deletes the account_analytic_plans write method ? I don't find the way to do it...

That would require to fully understand python pattern designs,

As the method modifications are share by the class holding the module,
you should have to look for a way to use the top method in osv.osv.write() or Models.write()

instead of using the super(class, self).write() because this would call the actual method 
that you would be wanting to override.

MRO and pattern design and digging into odoo code is required.
