### ISSUE TITLE
website_blog_rss to OCA

### ISSUE THREAD

**Issue by rafaelbn** [Vauxoo/addons-vauxoo#985]
Hi @nhomar ,

Could you / we move this https://github.com/Vauxoo/addons-vauxoo/tree/8.0/website_blog_rss to OCA?

Thanks

**Comment by nhomar** [comment]
Hello Rafael.

This module is part of a big site we are building... It is in plans but
after we finish the release.

I strongly recommend please make PR to our repository and once we finish
the big protect I dedicate to the proper migration.

But if you report issues and make PR to our repo my customer will be happy
because they see the benefit of opensource things...

But today I do not have the time to achieve the move, and I do not have the
time to wait Oca approval times to make quick fixes I prefer wait (and I
have some good pending points which will improve the module itself)

Btw I hear opinions but that's our situation now with such module.

On Friday, 10 June 2016, Rafael Blasco notifications@github.com wrote:

> Hi @nhomar https://github.com/nhomar ,
> 
> Could you / we move this
> https://github.com/Vauxoo/addons-vauxoo/tree/8.0/website_blog_rss to OCA?
> 
> Thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/Vauxoo/addons-vauxoo/issues/985, or mute the thread
> https://github.com/notifications/unsubscribe/AAUqyj80vW54kKLL2-V6_2KjaIJ0Po3fks5qKWmJgaJpZM4Iy9gt
> .

## 

Sent from my mobile.

**Comment by rafaelbn** [comment]
OK, thanks,

We are using this module in a customer for some time. We can quick move it and merge without your time and maintaining all origins and authors.

Please @yajo take care about @nhomar comments.

**Comment by nhomar** [comment]
On Fri, Jun 10, 2016 at 10:02 AM, Rafael Blasco notifications@github.com
wrote:

> We are using this module in a customer for some time. We can quick move it
> and merge without your time and maintaining all origins and authors.

Do you have any problem declaring addons-vauxoo into your environment? if
you find any problem please let us know also and help us to have this
repository clean too!.

## 

Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by rafaelbn** [comment]
OK
